apiVersion: v1
kind: ConfigMap
metadata:
  name: hse-config
data:
  NODE_ENV: "production"
  PORT: "3001"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  CLIENT_URL: "https://hse.digital"
  CORS_ORIGIN: "https://hse.digital,https://www.hse.digital"
