apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hse-production

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - redis-deployment.yaml
  - configmap.yaml
  - pvc.yaml
  - hpa.yaml
  - serviceaccount.yaml

images:
  - name: app-image
    newName: ghcr.io/your-org/hse-digital
    newTag: latest

commonLabels:
  app.kubernetes.io/name: hse-digital
  app.kubernetes.io/managed-by: kustomize
